name=High P-Code Graph Viewer
description=An experimental Ghidra plugin for research and reverse engineering. It adds a window that visualizes the High P-Code graph for the current function.
author=
createdOn=
version=@extversion@
